import { derived, invented } from './provenance';

/**
 * The smallest non-colour half of a `TokenSet` that `TokenSetSchema` accepts, shared by every test
 * file that has to build a whole one.
 *
 * Four files need it: `token-set.test.ts`, `strictness.test.ts`, `purity.test.ts`, and
 * `brand-record.test.ts`. Inline copies are the repo's older habit and they were fine at two ramps
 * and one alias. Nine categories is forty lines apiece, which would be four identical edits with
 * nothing to catch the file somebody forgot.
 *
 * #9 turned out not to add a tenth category. It put a provenance payload under `$extensions` on
 * every leaf the schema already had, so this fixture grew a builder call per leaf rather than a
 * new top-level key.
 *
 * Written out as literals rather than built from `systemConstants()` or the derivations. A fixture
 * generated by the code under test passes whatever that code does, which is how a wrong schema and
 * a wrong derivation agree with each other and no test notices. The one exception is the payload
 * itself: `provenance.ts` is the single place that spells the namespace, so each leaf calls
 * `derived`/`invented` rather than writing the object literal a typo could misspell there too.
 *
 * Not a `.test.ts` file, because the Vitest include glob would run it and it holds no tests.
 */

/** Spread into both scheme halves as well as the top level; `token-set.ts` records why. */
export const SHADOW_FIXTURE = {
	source: 'derived',
	values: {
		md: {
			color: { l: 0.15, c: 0.02, h: 259.8, alpha: 0.1 },
			offsetX: { value: 0, unit: 'px' },
			offsetY: { value: 4, unit: 'px' },
			blur: { value: 6, unit: 'px' },
			spread: { value: -1, unit: 'px' },
			$extensions: derived(
				'shadowCharacter',
				'tints the shadow from the measured spread and surface',
			),
		},
	},
} as const;

/** The eight categories that sit at the top level only, because none of them varies by scheme. */
export const NON_COLOR_FIXTURE = {
	radius: {
		source: 'derived',
		values: {
			lg: {
				value: 0.625,
				unit: 'rem',
				$extensions: derived('radiusCharacter', 'sets the corner radius from the measured base'),
			},
		},
	},
	typography: {
		source: 'derived',
		values: {
			size: {
				base: {
					value: 1,
					unit: 'rem',
					$extensions: derived(
						'typeScaleRatio',
						'sets the base size from the measured scale ratio',
					),
				},
			},
			weight: {
				regular: {
					value: 400,
					$extensions: invented('the schema requires a weight set that no seed field measures'),
				},
			},
			lineHeight: {
				normal: {
					value: 1.5,
					$extensions: invented(
						'the schema requires a line height set that no seed field measures',
					),
				},
			},
		},
	},
	tracking: {
		source: 'derived',
		values: {
			normal: {
				value: 0,
				unit: 'em',
				$extensions: derived('trackingFeel', 'shifts the tracking scale by the stated feel'),
			},
		},
	},
	spacing: {
		source: 'system',
		values: {
			md: {
				value: 1,
				unit: 'rem',
				$extensions: invented('the schema requires a spacing scale that no seed field measures'),
			},
		},
	},
	opacity: {
		source: 'system',
		values: {
			disabled: {
				value: 0.5,
				$extensions: invented('the schema requires a disabled opacity that no seed field measures'),
			},
		},
	},
	motion: {
		source: 'system',
		values: {
			duration: {
				fast: {
					value: 150,
					unit: 'ms',
					$extensions: invented('the schema requires a duration set that no seed field measures'),
				},
			},
			easing: {
				standard: {
					value: [0.2, 0, 0, 1],
					$extensions: invented('the schema requires an easing set that no seed field measures'),
				},
			},
		},
	},
	focusRing: {
		source: 'system',
		values: {
			width: {
				value: 3,
				unit: 'px',
				$extensions: invented('the schema requires a focus ring width that no seed field measures'),
			},
			offset: {
				value: 0,
				unit: 'px',
				$extensions: invented(
					'the schema requires a focus ring offset that no seed field measures',
				),
			},
		},
	},
	zIndex: {
		source: 'system',
		values: {
			modal: {
				value: 1300,
				$extensions: invented('the schema requires a modal layer that no seed field measures'),
			},
		},
	},
} as const;
