/**
 * The smallest non-colour half of a `TokenSet` that `TokenSetSchema` accepts, shared by every test
 * file that has to build a whole one.
 *
 * Four files need it: `token-set.test.ts`, `strictness.test.ts`, `purity.test.ts`, and
 * `brand-record.test.ts`. Inline copies are the repo's older habit and they were fine at two ramps
 * and one alias. Nine categories is forty lines apiece, and #9 adds a tenth, which would be four
 * identical edits with nothing to catch the file somebody forgot.
 *
 * Written out as literals rather than built from `systemConstants()` or the derivations. A fixture
 * generated by the code under test passes whatever that code does, which is how a wrong schema and
 * a wrong derivation agree with each other and no test notices.
 *
 * Not a `.test.ts` file, because the Vitest include glob would run it and it holds no tests.
 */

/** Spread into both scheme halves as well as the top level; `token-set.ts` records why. */
export const SHADOW_FIXTURE = {
	source: 'derived',
	values: {
		md: {
			color: { l: 0.15, c: 0.02, h: 259.8, alpha: 0.1 },
			offsetX: { value: 0, unit: 'px' },
			offsetY: { value: 4, unit: 'px' },
			blur: { value: 6, unit: 'px' },
			spread: { value: -1, unit: 'px' },
		},
	},
} as const;

/** The eight categories that sit at the top level only, because none of them varies by scheme. */
export const NON_COLOR_FIXTURE = {
	radius: { source: 'derived', values: { lg: { value: 0.625, unit: 'rem' } } },
	typography: {
		source: 'derived',
		values: {
			size: { base: { value: 1, unit: 'rem' } },
			weight: { regular: 400 },
			lineHeight: { normal: 1.5 },
		},
	},
	tracking: { source: 'derived', values: { normal: { value: 0, unit: 'em' } } },
	spacing: { source: 'system', values: { md: { value: 1, unit: 'rem' } } },
	opacity: { source: 'system', values: { disabled: 0.5 } },
	motion: {
		source: 'system',
		values: {
			duration: { fast: { value: 150, unit: 'ms' } },
			easing: { standard: [0.2, 0, 0, 1] },
		},
	},
	focusRing: {
		source: 'system',
		values: { width: { value: 3, unit: 'px' }, offset: { value: 0, unit: 'px' } },
	},
	zIndex: { source: 'system', values: { modal: 1300 } },
} as const;
