// Generated by scripts/build-dtcg-validator.mjs from core/dtcg/format.2025.10.json.
// Do not edit. Run `pnpm dtcg:build` instead.

export type DtcgSchemaError = {
	instancePath: string;
	schemaPath: string;
	keyword: string;
	message?: string;
	params: Record<string, unknown>;
};

export type DtcgSchemaValidator = ((data: unknown) => boolean) & {
	errors?: DtcgSchemaError[] | null;
};

export declare const validate: DtcgSchemaValidator;
export default validate;
